/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aprilasr;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void apiCanInitialize() {
        AprilAsrNative.aam_api_init(AprilAsrNative.APRIL_VERSION);
    }
}
