/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aprilasr;

import com.sun.jna.Pointer;
import com.sun.jna.NativeLong;
import com.sun.jna.CallbackReference;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void canLoadModel() {
        Pointer model = AprilAsrNative.aam_create_model("/home/hp/Downloads/aprilv0_en-us.april");
        assertNotNull(model);

        AprilAsrNative.aam_free(model);
    }

    @Test void cantLoadFakeModel() {
        Pointer fake_model = AprilAsrNative.aam_create_model("/tmp/fake123");
        assertNull(fake_model);
    }

    @Test void canUseModel() {
        Model wrapped_model = new Model("/home/hp/Downloads/aprilv0_en-us.april");
        assertEquals(16000, wrapped_model.getSampleRate());

        Session wrapped_session = new Session(wrapped_model);

        short[] blank = new short[16000];
        wrapped_session.feedPCM16(blank, 1792);
    }
}
